spring:
  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wjdthddl
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # 최대 커넥션 개수
      connection-timeout: 30000 # 커넥션 얻기위해 대기하는 최대 시간(ms)
      max-lifetime: 180000 # 커넥션 최대 수명(ms)

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마(테이블) 처리 전략
      # none: 아무 작업도 하지 않음 (운영 환경 추천)
      # create: 기존 테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      ddl-auto: update
    properties:
      hibernate:
        # MySQL 8 버전에 맞는 Dialect(방언) 설정
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        show_sql: true

  # 로깅 레벨 설정
  logging:
    level:
      # Hibernate가 실행하는 SQL 쿼리를 DEBUG 레벨로 로그에 출력
      org.hibernate.SQL: DEBUG

  # classpath = resources 경로 가리킴
  # flyway 효과로 locations 경로의 sql 파일을 서버실행시 대신 수행지원
  # sql 파일 생성시 여러개있으면 맨앞 V[버전명] 다르게 해야 오류안남 EX) V1 중복 있으면 오류이니 V1, V2 생성
  flyway:
    enabled: true
    locations: classpath:db/migration

# 내장 웹 서버 설정
server:
  port: 8080

# (선택)Swagger UI 설정 (실제 라이브에서는 노출위험 방지하고자 false 권장)
springdoc:
  swagger-ui:
    enabled: true